### ISSUE TITLE
Preparations

### ISSUE THREAD

**Issue by HuangJiaLian** [HuangJiaLian/DNN-ODE-Solver#2]
### Preparations

Before we get started, you should prepare the following things if you don't have all of them:

#### Todos
- [ ] Install Python environment: [Anaconda](https://www.anaconda.com/)
- [ ] Install the powerful python calculation package: [Numpy](https://numpy.org/)
- [ ] Install the visualization library: [Matplotlib](https://matplotlib.org/)
- [ ] Install machine learning toolkit: [TensorFlow](https://www.tensorflow.org/) 
- [ ] Write a testing python program under the folder named after your username.
- [ ] Finish the preparations section in `README.md` together.
- [ ] Install the Google Chrome plugin: [MathJax Plugin for Github](https://chrome.google.com/webstore/detail/mathjax-plugin-for-github/ioemnmodlmafdkllaclgeombjnmnbima?utm_source=chrome-ntp-icon)

#### Tips
- Numpy, Matplotlib, and Tensorflow are Python libraries.
- `pip` command is recommended to install Python libraries. 
- **MathJax Plugin for Github** is used for visualizing the LaTex formulas. 
- If you have any questions, leave comments below. 😊

**Comment by Fang-max** [comment]
从Pypl中选择tensorflow软件包进行安装：找不到软件包

**Comment by HuangJiaLian** [comment]
> 从Pypl中选择tensorflow软件包进行安装：找不到软件包

How to install TensorFlow? 
You can try to use **pip** to install Tensorflow.

<p align='center'>
<img src='https://raw.githubusercontent.com/HuangJiaLian/DataBase0/master/uPic/COoAUV.png' width=50%>
</p>

<p align='center'>
<img src='https://raw.githubusercontent.com/HuangJiaLian/DataBase0/master/uPic/EjYSXU.png' width=50%>
</p>

@Fang-max

**Comment by Fang-max** [comment]
第五步具体要做什么？

**Comment by HuangJiaLian** [comment]
> 第五步具体要做什么？

Write some simple code to make sure all the libraries are installed correctly.  
For example:
- To test Matplotlib, you can plot a `y = cos(x)`.
- To test Tensorflow, you can print the TensorFlow version.
- ...

@Fang-max

**Comment by Fang-max** [comment]
绘制图像需要安装其他程序吗？图像绘制不出来。

**Comment by HuangJiaLian** [comment]
> 绘制图像需要安装其他程序吗？图像绘制不出来。

You only need `Matplotlib`.

Try this testing code:

```python
import matplotlib.pyplot as plt 

x = [1,2,3,4,5,6,7,8]
y = [1,4,9,16,25,36,49,64]

plt.title('Hello Matplotlib.')
plt.xlabel('x')
plt.ylabel('y')
plt.grid()
plt.plot(x,y,label='$y = x^2$')
plt.legend()
plt.savefig('HelloPlt.png')
plt.savefig('HelloPlt.eps')
plt.show()
```

@Fang-max
