### ISSUE TITLE
The ODE we need to solve.

### ISSUE THREAD

**Issue by HuangJiaLian** [HuangJiaLian/DNN-ODE-Solver#3]
### Newton's Law of Cooling
The ordinary differential equation(ODE) describes the relationship between the target function and its derivatives. In this project, we choose a very simple equation to demonstrate the process to solve the ODE using the method of deep neural networks.

The ODE we are going to solve is as follow:
$$
\frac{dT}{dt} = 0.2(20-T)\\T_0 = C
$$, 
where $T_0 = C$ is the initial temrature when time $t=0$. We assume $C=5$ in this project. 

### Todo 📕
- [ ] Find the analytical solution for this ODE by yourself.
- [ ] Leave comments below. You should show your process to find the analytical solution. 
- [ ] Use Matplotlib to show the solution and save your image in `png` and `eps` format.
- [ ] Upload your code and images to your folder on this repository.

### Tips 
- This ODE comes from [Introduction to Dynamical Systems and Chaos](https://www.complexityexplorer.org/courses/105-introduction-to-dynamical-systems-and-chaos)
- If you have any questions, leave comments below, and have fun.  😊

**Comment by Fang-max** [comment]
师兄，怎么通过使用深度神经网络的方式来解这个方程呢？
@HuangJiaLian

**Comment by HuangJiaLian** [comment]
@Fang-max  可以先看看这个。https://github.com/maziarraissi/PINNs

**Comment by HuangJiaLian** [comment]
@Fang-max 这个也可以参考一下。程序可能需要更新，因为使用的是几年前的Tensorflow.  https://github.com/HuangJiaLian/use-tensorflow-to-solve-ode-pde

**Comment by HuangJiaLian** [comment]
使用TF 2.0 解方程 https://medium.com/analytics-vidhya/solving-differential-equation-by-a-neural-network-6a67d2a29d16
